### ISSUE TITLE
v2 tag missing

### ISSUE THREAD

**Issue by foxted** [myyk/git-democracy#846]
For v1, it was possible to pin to `v1` and not to a specific minor/patch version. This is not available for v2. 

This works: 

```
jobs:
  democracy:
    name: Democracy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Evaluate vote
        uses: myyk/git-democracy@v2.0.0
```

This doesn't (but should): 

```
jobs:
  democracy:
    name: Democracy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Evaluate vote
        uses: myyk/git-democracy@v2
```
